### ISSUE TITLE
Laravel 5.8 compatibility

### ISSUE THREAD

**Issue by ghost** [saleem-hadad/blogged#10]
Blogged is currently not compatible with Laravel 5.8.

`orchestra/database` is not completely compatible with Laravel 5.8 too, the compatible version is 3.8.x-dev.

Compatibility should be prepared:
- update the dependencies in `composer.json`
- fix code (tests do not pass)

I may work on it, but anyway, to have a stable release, we need to wait for `orchestra/database 3.8` to be released. Should be a matter of days now, since `orchestra/testbench 3.8` has been released on Feb 25.

**Comment by khiconit** [comment]
Same issue with Laravel 5.8

**Comment by adamthomason** [comment]
Any news on this? I tried to install but failed

**Comment by robertgarrigos** [comment]
Yep, shame.... :-(

**Comment by saleem-hadad** [comment]
I will work on this tonight guys :)

**Comment by saleem-hadad** [comment]
now available in v1.1 💃
