### ISSUE TITLE
HTTP 422 and Error message when trying to save Article

### ISSUE THREAD

**Issue by adamthomason** [saleem-hadad/blogged#21]
**Describe the bug**
When I try to save an article, either as a draft or publishing, I receive a 422 error, and the article doesn't save.

**Expected behavior**
The Article saves.

**Comment by saleem-hadad** [comment]
can you check the response errors?

**Comment by adamthomason** [comment]
`{"message":"The given data was invalid.","errors":{"image":["The image field is required."]}}`

However, there is no image field!

**Comment by adamthomason** [comment]
I've just realised that I'm an idiot. You click the image to upload an image. My bad, you can close this 😂

**Comment by saleem-hadad** [comment]
😂😂😂 no issue.
Have a nice day :D

may I know if it gives the right message feedback? cus I forgot :/
