### ISSUE TITLE
404 after changing blog route.

### ISSUE THREAD

**Issue by mforcer** [saleem-hadad/blogged#3]
**Describe the bug**
Changing the routes in `blogged.php` kills all pages with the exception of the public blog route.

**To Reproduce**
Changed routes to:

```
    'routes'        => [
        'blog'      => '', // ie. domain route
        'dashboard' => 'blog/dashboard',
        'login'     => 'login',
    ],

```

After doing this `/blog/dashboard/' and '/login/' throw a 404.

Looking at the source I can't see why this would happen.

**Expected behavior**
I'd expect to be able to go to domain route and see the blog, and `blog/dashboard` to access the back-end.

**Comment by saleem-hadad** [comment]
Fixed now and will be ready today in v1.0.1
Thanks for your help :-)
