### ISSUE TITLE
[Question] Contribution to documentation

### ISSUE THREAD

**Issue by ghost** [saleem-hadad/blogged#7]
Hi again,

Is there a way we may contribute to documentation?

**Comment by saleem-hadad** [comment]
Hi @Arcesilas 
thanks a lot for your help 
I've created a new repo which contains all the docs
https://github.com/saleem-hadad/blogged-docs

**Comment by ghost** [comment]
Great! Thanks, I'll certainly submit some PR (at least for the policies command ;) )
